wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: huggingface
    huggingface_version: 4.6.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.7.7
      5: 0.10.30
      6: 4.6.1
      8:
      - 5
asset_dir:
  desc: null
  value: asset/
batch_size:
  desc: null
  value: 64
cate_cols:
  desc: null
  value:
    KnowledgeTag: 913
    assessmentItemID: 9455
    testId: 1538
clip_grad:
  desc: null
  value: 10
column_seq:
  desc: null
  value:
  - assessmentItemID
  - testId
  - answerCode
  - KnowledgeTag
  - mask
cont_cols:
  desc: null
  value: []
data_dir:
  desc: null
  value: /opt/ml/input/data/train_dataset
device:
  desc: null
  value: cuda
drop_out:
  desc: null
  value: 0.2
exp_cfg:
  desc: null
  value: ./config/train/export/exported_config.json
fe_dir:
  desc: null
  value: ./features/
fe_set:
  desc: null
  value: default_FE.json
hidden_dim:
  desc: null
  value: 64
json:
  desc: null
  value: null
k_fold_idx:
  desc: null
  value: 0
log_steps:
  desc: null
  value: 50
lr:
  desc: null
  value: 0.0001
max_seq_len:
  desc: null
  value: 20
model:
  desc: null
  value: lstm
model_alias:
  desc: null
  value: ''
model_dir:
  desc: null
  value: models/
n_epochs:
  desc: null
  value: 20
n_heads:
  desc: null
  value: 2
n_layers:
  desc: null
  value: 2
no_select:
  desc: null
  value: true
num_workers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: adam
patience:
  desc: null
  value: 5
pin_mem:
  desc: null
  value: true
save_suffix:
  desc: null
  value: ''
scheduler:
  desc: null
  value: plateau
seed:
  desc: null
  value: 42
test_data:
  desc: null
  value: test_data.csv
train_data:
  desc: null
  value: cv_train_data.csv
val_data:
  desc: null
  value: null
